FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY target/EmployeeManagement-0.0.1-SNAPSHOT.jar EmployeeManagement-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "EmployeeManagement-0.0.1-SNAPSHOT.jar"]
